name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    container: gcc:9

    steps:
    - uses: actions/checkout@v1
    - name: make
      run: make RELEASE=1
    - name: make install
      run: make install DESTDIR=dist
    - name: Zip Release
      uses: TheDoctor0/zip-release@v0.2.1
      with:
        filename: dist.zip
        path: dist
        exclusions: dist/.keep dist/mods/.keep
    - name: Action Release
      uses: yakuhzi/action-release@v1.2.0
      with:
        file: dist.zip