name: C/C++ CI

on: [push]

jobs:
  build:
    strategy:
      matrix:
        mode: [DEBUG, RELEASE]

    runs-on: ubuntu-latest
    container: gcc:9

    steps:
    - uses: actions/checkout@v1
    - name: make ${{ matrix.mode }}
      run: make ${{ matrix.mode }}=1
    - name: make install
      run: make install ${{ matrix.mode }}=1 DESTDIR=dist-${{ matrix.mode }}
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: dist-${{ matrix.mode }}
        path: dist-${{ matrix.mode }}